language: csharp
solution: HelloOwin.sln
mono:
  - latest
install:
  - nuget restore HelloOwin.sln
script:
  - xbuild /p:Configuration=Release HelloOwin.sln
  - mono ./packages/xunit.runner.console.*/tools/net461/xunit.console.exe ./HelloOwinTests/bin/Release/HelloOwinTests.dll
