version: 1.0.{build}
clone_depth: 1
cache:
- packages -> **\packages.config
before_build:
- nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
