# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

variables:
  solution: 'HelloOwin.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: 'csharpWindows'
    pool:
      vmImage: 'windows-latest'
    displayName: 'C# (Windows)'

    steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tools'

      - task: VisualStudioTestPlatformInstaller@1
        inputs:
          packageFeedSelector: 'nugetOrg'
          versionSelector: 'latestStable'

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
        displayName: 'NuGet Restore'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
        displayName: 'Build'

      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **/*tests.dll
            !**/*TestAdapter.dll
            !**/obj/** 
          runTestsInIsolation: True
          codeCoverageEnabled: True
        displayName: 'Test'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'vstest'
          testResultsFiles: '**/*.trx'
          searchFolder: '$(Agent.TempDirectory)'
          failTaskOnFailedTests: True
          publishRunAttachments: True
          buildPlatform: '$(buildPlatform)'
          buildConfiguration: '$(buildConfiguration)'
        displayName: 'Publish Test Results'

  - job: 'csharpLinux'
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'C# (Linux)'

    steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tools'

      - script: |
          mono --version
          msbuild /version
          nuget --version
          dotnet --info | grep 'Base Path'
          ls /usr/share/dotnet/shared/Microsoft.NETCore.App/
        displayName: 'Environment Info'

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
        displayName: 'NuGet Restore'

      - script: |
          msbuild /p:Configuration=$(buildConfiguration) $(solution)
        displayName: 'Build'

      - script: |
          ./test.sh $(buildConfiguration)
        displayName: 'Test'
