# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

variables:
  solution: 'HelloOwin.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: 'csharpWindows'
    pool:
      vmImage: 'vs2017-win2016'
    displayName: 'C# (Windows)'

    steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tools'

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
        displayName: 'NuGet Restore'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
        displayName: 'Build'

      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          codeCoverageEnabled: True
        displayName: 'Test'

  - job: 'csharpLinux'
    pool:
      vmImage: 'ubuntu-16.04'
    displayName: 'C# (Linux)'

    steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tools'

      - script: |
          mono --version
          msbuild /version
          nuget --version
          dotnet --info | grep 'Base Path'
          ls /usr/share/dotnet/shared/Microsoft.NETCore.App/
        displayName: 'Environment Info'

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
        displayName: 'NuGet Restore'

      - script: |
          msbuild /p:Configuration=$(buildConfiguration) $(solution)
        displayName: 'Build'

      - script: |
          ./test.sh $(buildConfiguration)
        displayName: 'Test'
