name: .NET Core

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '3.1.x', '5.0.x' ]
        os: [ 'windows-latest', 'ubuntu-latest' ]
    name: DotNet ${{ matrix.dotnet }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear
      - name: NuGet Restore
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release
